# Generated by Django 6.0.4 on 2026-05-02 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['-term', 'course__code']},
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='term',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'professor', 'term')},
        ),
    ]
