# Generated by Django 6.0.4 on 2026-05-04 19:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseoffering_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='term',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Term format must be like 1405-1', regex='^\\d{4}-[1-3]$')]),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='term',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Term format must be like 1405-1', regex='^\\d{4}-[1-3]$')]),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'professor', 'term'), name='uniq_course_prof_term'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'offering'), name='uniq_student_offering'),
        ),
    ]
