# Generated by Django 6.0.4 on 2026-05-30 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='term',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Term format must be like 1405-1', regex='^\\d{4}-[1-3]$')]),
        ),
    ]
