# Generated by Django 6.0.4 on 2026-05-04 19:19

import resources.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/', validators=[resources.validators.validate_file_extension, resources.validators.validate_file_size]),
        ),
    ]
